name: Documentation Issue
description: Report a documentation problem or suggest improvements
title: "[Docs]: "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve Prax documentation! 📚

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect documentation
        - Unclear documentation
        - Outdated documentation
        - Typo or grammar
        - New example needed
        - API docs improvement
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the documentation located?
      placeholder: "https://prax.rs/docs/queries or src/lib.rs line 123"
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Content
      description: What does the current documentation say (if applicable)?
      placeholder: Paste the current text or describe what's there...

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        The documentation should explain...

        Example:
        ```rust
        // Better example here
        ```
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR to fix this documentation


