name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: I would like Prax to...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API
      description: If applicable, show how the feature might be used.
      render: rust
      placeholder: |
        // Example of how the feature would be used
        let result = client
            .user()
            .new_feature()
            .exec()
            .await?;

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered...

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Which part of Prax does this affect?
      options:
        - Query Builder
        - Schema / Models
        - Migrations
        - CLI
        - PostgreSQL Driver
        - MySQL Driver
        - SQLite Driver
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this require a breaking change?
      options:
        - "No"
        - "Yes"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I would be willing to submit a PR for this feature

